# config/model_config.py

# --- Target Column ---
# The name of the target variable column after running make_supervised
Y_COL = 'y'

# --- Feature List ---
# A comprehensive list of features generated by features/feature_engineering.py
# This list can be imported and used by other scripts for consistent feature selection.
FEATURES = [
    'return', 'return_lag_2', 'return_lag_3', 'return_lag_5', 'return_lag_10',
    'atr_14', 'rsi_14', 'adx', 'adx_pos', 'adx_neg',
    'volatility_10', 'volatility_20', 'cci_20',
    'vol_lag_2', 'vol_lag_5', 'rsi_7', 'rsi_21',
    'vol_ma20', 'vol_ratio', 'bb_mavg', 'bb_hband', 'bb_lband',
    'obv', 'roc_10', 'williams_r', 'stoch_k', 'stoch_d',
    'macd', 'macd_signal',
    'close_to_sma20_ratio', 'close_to_ema50_ratio', 'ema5_to_ema20_ratio',
    'sma10_to_sma50_spread_norm', 'roc_10_norm_by_atr', 'adx_x_rsi',
    'hour_of_day', 'day_of_week',
    'prob_bull', 'prob_bear', 'prob_ranging',
    'sent_mean', 'sent_median', 'count'
]

# --- Model Hyperparameter Search Spaces ---
# Used by Optuna for hyperparameter tuning.
MODEL_PARAMS = {
    "logreg": {
        "solver": "lbfgs",
        "max_iter": 1000,
        "use_scaler": True,
        # Optuna search space
        "C_range": [1e-3, 1e2],
        "buy_th_range": [0.51, 0.7],
        "sell_th_range": [0.3, 0.49],
        "fee_range": [0.0002, 0.001]
    },
    "rf": {
        # Optuna search space
        "n_estimators_range": [100, 1000],
        "max_depth_range": [3, 20],
        "min_samples_leaf_range": [1, 10]
    },
    "lgb": {
        # Optuna search space
        "n_estimators_range": [100, 1000],
        "num_leaves_range": [20, 150],
        "learning_rate_range": [0.01, 0.3],
        "max_depth_range": [3, 15],
        "min_child_samples_range": [20, 100]
    }
}

# --- Evolution (Optuna) Settings ---
DIRECTION = 'maximize'
METRIC_TO_OPTIMIZE = 'sharpe_ratio' # or 'profit_factor', 'win_rate', etc.
N_TRIALS = 100

# --- Feature Generation Parameters ---
# Used by features/feature_engineering.py to dynamically generate features.
FEATURE_PARAMS = {
    "lag_windows": [2, 3, 5, 10, 15, 20],
    "ma_windows": [10, 20, 30, 50, 100, 200],
    "rsi_windows": [7, 14, 21, 30],
    "volatility_windows": [10, 20, 30, 60, 120],
    "other_indicator_windows": [14, 20, 30],
}
