import os
import logging
import requests
import json
from typing import Optional

class Notifier:
    """
    Generic Notification Manager.
    Supports: WeCom (Enterprise WeChat), PushPlus
    """
    def __init__(self):
        self.logger = logging.getLogger("Notifier")
        self.pushplus_token = os.getenv("PUSHPLUS_TOKEN", "")
        
    # Discord Config
        self.discord_webhook = os.getenv("DISCORD_WEBHOOK", "")
        
    def send(self, title: str, content: str, template: str = "markdown"):
        """
        Send notification. Priority: Discord > Feishu (Deprecated) > WeCom > PushPlus.
        """
        if self.discord_webhook:
            self._send_discord(title, content)
        elif self.wecom_cid and self.wecom_secret:
            self._send_wecom(title, content)
        elif self.pushplus_token:
            self._send_pushplus(title, content, template)
        else:
            self.logger.warning("No notification tokens configured. Notification skipped.")

    def _send_discord(self, title: str, content: str):
        """
        Send message via Discord Webhook
        """
        try:
            # Discord uses 'embeds' for rich text
            # Content > 2000 chars needs to be split, but our briefing is usually short enough for Embed Description (4096 limit)
            
            # Determine color based on title (Alert = Red, Update = Blue)
            color = 0xFF0000 if "Alert" in title or "Shift" in title else 0x3498DB
            
            payload = {
                "username": "AutoTrader Bot",
                "embeds": [
                    {
                        "title": title,
                        "description": content,
                        "color": color,
                        "footer": {
                            "text": "Generated by Gemma 3 & Auto-Trader"
                        }
                    }
                ]
            }
            
            r = requests.post(self.discord_webhook, json=payload, timeout=10)
            
            if r.status_code in [200, 204]:
                self.logger.info(f"✅ Notification sent via Discord: {title}")
            else:
                self.logger.error(f"❌ Discord Send Error: {r.status_code} - {r.text}")
                
        except Exception as e:
            self.logger.error(f"❌ Failed to send Discord notification: {e}")

    def _send_feishu(self, title: str, content: str):
        # Deprecated but kept for backward compatibility if needed
        pass

    def _send_wecom(self, title: str, content: str):
        """
        Send message via Enterprise WeChat (WeCom)
        Docs: https://developer.work.weixin.qq.com/document/path/90236
        """
        try:
            # 1. Get Access Token
            token_url = f"https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={self.wecom_cid}&corpsecret={self.wecom_secret}"
            r = requests.get(token_url, timeout=10)
            token_data = r.json()
            
            if token_data.get('errcode') != 0:
                self.logger.error(f"❌ WeCom Token Error: {token_data}")
                return
                
            access_token = token_data.get('access_token')
            
            # 2. Send Message (Markdown)
            send_url = f"https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={access_token}"
            
            # WeCom Markdown Format: Only supports bold, italic, link, code.
            # Convert title to bold header
            md_content = f"# {title}\n\n{content}"
            
            payload = {
                "touser": "@all",
                "msgtype": "markdown",
                "agentid": self.wecom_aid,
                "markdown": {
                    "content": md_content
                }
            }
            
            r = requests.post(send_url, json=payload, timeout=10)
            resp = r.json()
            
            if resp.get('errcode') == 0:
                self.logger.info(f"✅ Notification sent via WeCom: {title}")
            else:
                self.logger.error(f"❌ WeCom Send Error: {resp}")
                
        except Exception as e:
            self.logger.error(f"❌ Failed to send WeCom notification: {e}")

    def _send_pushplus(self, title: str, content: str, template: str):
        """
        Send message via PushPlus (http://www.pushplus.plus/)
        """
        url = "http://www.pushplus.plus/send"
        
        # PushPlus expects 'content' to be the body.
        # If template is markdown, we should ensure content is formatted correctly.
        
        payload = {
            "token": self.pushplus_token,
            "title": title,
            "content": content,
            "template": template
        }
        
        try:
            response = requests.post(url, json=payload, timeout=10)
            resp_json = response.json()
            
            if resp_json.get("code") == 200:
                self.logger.info(f"✅ Notification sent via PushPlus: {title}")
            else:
                self.logger.error(f"❌ PushPlus failed: {resp_json}")
                
        except Exception as e:
            self.logger.error(f"❌ Failed to send PushPlus notification: {e}")

# Global instance
_notifier_instance = None

def get_notifier():
    global _notifier_instance
    if _notifier_instance is None:
        _notifier_instance = Notifier()
    return _notifier_instance
